# install nginx and start nginx on multiple servers.
# To run this playbook use command ansible-playbook 
---

- name: Install & start nginx
  hosts: webserver   # take hosts from inventory file.
  # hosts: all  # For all hosts
  # hosts: 172.31.1.1:172.52.78.1 # Give multiple host
  # hosts: webserver:database:anyothergroup  # Give multiple groups

  become: yes  # which user to run the commands

  tasks:
    - name: Install nginx
      # shell: apt install nginx 
      apt:    # apt is also an module in nginx like shell & copy
        name: nginx
        state: present

    - name: Start nginx
      # shell: systemctl start nginx 
      service:    # service is also an module in nginx like shell & copy
        name: nginx
        state: started
