---
- name: Install and Start Nginx on Ubuntu and Amazon Linux 2
  hosts: all
  become: yes  # Ensure to run tasks with sudo or as root

  tasks:
    - name: Gather OS facts
      setup:  # Gather all facts, including distribution
      register: facts

    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: present
      when: facts.ansible_facts['ansible_distribution'] == 'Ubuntu'

    - name: Install Nginx on Amazon Linux 2
      dnf:
        name: nginx
        state: present
      when: facts.ansible_facts['ansible_distribution'] == 'Amazon'

    - name: Start Nginx Service
      service:
        name: nginx
        state: started
