 ---
- name: Install and Start Nginx on Ubuntu and Add Users
  hosts: all
  become: yes  # Ensure to run tasks with sudo or as root
  
  vars:
    package: nginx
    package2: tree
    new_users:
      - varun
      - alice
      - bob

  tasks:
    - name: Gather OS facts
      setup:  # Gather all facts, including distribution
      register: facts

    - name: Install Nginx on Ubuntu
      apt:
        name: '{{package}}'
        state: present
      when: facts.ansible_facts['ansible_distribution'] == 'Ubuntu'
      notify: Start Nginx Service  # Notify will call the handler with the same name.

    - name: Add Multiple Users
      user:
        name: "{{ item }}"
        state: present
      with_items: "{{ new_users }}"
      # with_items:
      #   - varun
      #   - alice
      #   - bob
      become: yes

  handlers:
    - name: Start Nginx Service
      service:
        name: '{{package}}'
        state: started
